services:
  db:
    image: mariadb:10.5
    container_name: rathena_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rathena
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarokpass
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql-files:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rathena:
    build: .
    container_name: rathena_server
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rathena
      - ./conf:/rathena/conf
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
    command: >
      sh -c "./login-server & ./char-server & ./map-server && tail -f /dev/null"
